-- EXCEL MASTER — COMPLETE SUPABASE SCHEMA / REPAIR
-- Run this entire file once in Supabase > SQL Editor.
-- Safe for the existing project: it creates missing objects and refreshes RLS policies.
-- NEVER put a password or service_role/secret key in GitHub.

create extension if not exists pgcrypto;

-- =========================================================
-- 1) PROFILES
-- =========================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'agent' check (role in ('agent','admin')),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(coalesce(new.email,''),'@',1)),
    'agent'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Repair profiles for users that already exist.
insert into public.profiles (id, full_name, role)
select
  u.id,
  coalesce(u.raw_user_meta_data->>'full_name', split_part(coalesce(u.email,''),'@',1)),
  'agent'
from auth.users u
where not exists (select 1 from public.profiles p where p.id=u.id)
on conflict (id) do nothing;

-- =========================================================
-- 2) TRAINING SUBMISSIONS
-- =========================================================
create table if not exists public.training_submissions (
  id uuid primary key default gen_random_uuid(),
  formula_name text not null,
  title text not null,
  explanation text not null,
  sample_data text,
  formula_example text not null,
  expected_result text,
  common_mistakes text,
  practice_question text,
  practice_answer text,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  review_note text,
  created_at timestamptz not null default now(),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz
);

-- =========================================================
-- 3) LIVE AGENT PRESENCE
-- =========================================================
create table if not exists public.agent_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  status text not null default 'online' check (status in ('online','offline')),
  current_page text,
  current_formula text,
  last_activity text,
  last_seen timestamptz not null default now(),
  user_agent text,
  updated_at timestamptz not null default now()
);

create index if not exists agent_presence_last_seen_idx
on public.agent_presence(last_seen desc);

-- =========================================================
-- 4) AGENT ACTIVITY FEED
-- =========================================================
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  agent_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  formula_name text,
  details text,
  created_at timestamptz not null default now()
);

create index if not exists activity_logs_created_at_idx
on public.activity_logs(created_at desc);

create index if not exists activity_logs_agent_idx
on public.activity_logs(agent_id);

-- =========================================================
-- 5) ADMIN CHECK
-- =========================================================
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- =========================================================
-- 6) RLS
-- =========================================================
alter table public.profiles enable row level security;
alter table public.training_submissions enable row level security;
alter table public.agent_presence enable row level security;
alter table public.activity_logs enable row level security;

-- PROFILES
drop policy if exists "profile self read" on public.profiles;
drop policy if exists "profiles_self_or_admin" on public.profiles;
drop policy if exists "profiles_admin_read" on public.profiles;

create policy "profiles_self_or_admin"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.is_admin());

-- No agent insert/update/delete policy on profiles.
-- Roles can only be changed by the database owner/Supabase SQL Editor.

-- TRAINING SUBMISSIONS
drop policy if exists "training read approved own admin" on public.training_submissions;
drop policy if exists "training insert own pending" on public.training_submissions;
drop policy if exists "training admin update" on public.training_submissions;
drop policy if exists "training admin delete" on public.training_submissions;
drop policy if exists "training_admin_select" on public.training_submissions;

create policy "training_select"
on public.training_submissions
for select
to authenticated
using (
  status = 'approved'
  or author_id = auth.uid()
  or public.is_admin()
);

create policy "training_insert_own_pending"
on public.training_submissions
for insert
to authenticated
with check (
  author_id = auth.uid()
  and status = 'pending'
);

create policy "training_admin_update"
on public.training_submissions
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "training_admin_delete"
on public.training_submissions
for delete
to authenticated
using (public.is_admin());

-- AGENT PRESENCE
drop policy if exists "presence_self_write" on public.agent_presence;
drop policy if exists "presence_admin_read" on public.agent_presence;
drop policy if exists "presence_self_or_admin_read" on public.agent_presence;

create policy "presence_self_write"
on public.agent_presence
for insert
to authenticated
with check (user_id = auth.uid());

create policy "presence_self_update"
on public.agent_presence
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "presence_self_or_admin_read"
on public.agent_presence
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

-- ACTIVITY LOGS
drop policy if exists "activity_self_insert" on public.activity_logs;
drop policy if exists "activity_admin_read" on public.activity_logs;

create policy "activity_self_insert"
on public.activity_logs
for insert
to authenticated
with check (agent_id = auth.uid());

create policy "activity_admin_read"
on public.activity_logs
for select
to authenticated
using (public.is_admin());

-- Agents must not edit/delete activity history.
-- Admin does not need to delete activity from the dashboard.

-- =========================================================
-- 7) GRANTS
-- =========================================================
-- These grants fix the "permission denied for table training_submissions"
-- error when the authenticated client queries the table.
grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.training_submissions to authenticated;
grant select, insert, update on public.agent_presence to authenticated;
grant select, insert on public.activity_logs to authenticated;

-- =========================================================
-- 8) OWNER / ADMIN
-- =========================================================
-- This is the existing Owner UUID in the project.
-- If this is your actual Owner Auth user, run:
update public.profiles
set role = 'admin'
where id = '7487289c-95a8-480d-af95-e2965774f1c4';

-- Optional verification:
-- select id, full_name, role from public.profiles order by created_at desc;
-- select * from public.agent_presence order by last_seen desc;
-- select * from public.activity_logs order by created_at desc limit 20;

-- =========================================================
-- 9) OPTIONAL REALTIME
-- =========================================================
-- The dashboard already polls every 15 seconds, so Realtime is not required.
-- If you want instant Realtime later, enable these tables in Supabase
-- Database > Replication > supabase_realtime:
-- public.agent_presence
-- public.activity_logs
